### ISSUE TITLE
Question: Where I can find app_id in app.fullstory.com

### ISSUE THREAD

**Issue by jarzimichal** [CaliStyle/ng-fullstory#1]
Hi,

I have a question about configuring the ng-fullstory module in my code.
Where can I find the <your_app_id> from app.fullstory.com

They provide recording snippet however I can't see any app_id there.
It's a bit unclear to me how to use it. 
Will appreciate your help. 

```
FullstoryModule.forRoot({
      appId: <your_app_id>, // from your Fullstory config
      updateOnRouterChange: true // will automatically run `update` on router event changes. Default: `false`
    })
```

Thanks,
Michal.

**Comment by scott-wyatt** [comment]
Hi, sorry, I still need to update the directions. I’ll do that later today.

**Comment by scott-wyatt** [comment]
Okay, directions are updated.  the argument is `fsOrg: <your fsOrg id>`
